apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gigg-resizer.fullname" . }}
  labels:
    {{- include "gigg-resizer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gigg-resizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gigg-resizer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gigg-resizer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if .Values.externalStorage.enabled }}
      volumes:
        - name: {{ include "gigg-resizer.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ include "gigg-resizer.fullname" . }}-pvc
      {{end}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--port={{ .Values.service.port }}"
            - "--timeout={{ .Values.timeoutSeconds }}"
            - "--loglvl={{ .Values.loglvl }}"
            - "--memory-limit={{ .Values.memoryLimit }}"
            {{ if .Values.externalStorage.enabled }}
            - "--working-directory='{{ .Values.externalStorage.mountPath }}'"
            {{end}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          {{ if .Values.externalStorage.enabled }}
          volumeMounts:
            - mountPath: {{.Values.externalStorage.mountPath}}
              name: {{ include "gigg-resizer.fullname" . }}-volume
          {{end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
