{{- if .Values.externalStorage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gigg-resizer.fullname" . }}-pvc
  labels:
    {{- include "gigg-resizer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.externalStorage.size }}
{{- end }}