name: Docker Build and Push

on:
  push:
    tags:
      - 'gigg-resizer-*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract version from git tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/gigg-resizer-}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            random1st/imagemagick:${{ steps.get_version.outputs.VERSION }}
            random1st/imagemagick:latest
